### ISSUE TITLE
AWS Quickstart Failed initializing the control plane

### ISSUE THREAD

**Issue by rbankston** [heptio/aws-quickstart#223]
**What steps did you take and what happened:**

Used `Launch Latest Quickstart Now` in two different regions. Both US-East-2 and US-West-2 failed with the error message in the cloud init output log of:

```
+ /usr/local/bin/cfn-init --verbose --stack Heptio-Kubernetes-K8sStack-I54YC612LLPR --region us-west-2 --resource K8sMasterInstance --configsets master-setup
Error occurred during build: Command 04-master-setup failed
```

When running `/tmp/setup-k8s-master.sh` on a node that failed it errors with the command:

```
# Initialize master node
kubeadm init --config /tmp/kubeadm.yaml
unable to decode config from bytes: couldn't unmarshal YAML: yaml: line 9: could not find expected ':'
```

**What did you expect to happen:**
The master to be initialized.

**Environment:**

- Kubernetes version: (use `kubectl version`): Current Latest within Quickstart
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by rbankston** [comment]
Did some further testing. When copying and pasting the same yaml into the same file the kubeadm init works without issue. When called from the script it fails with that error. Tested on three attempts all same result.

**Comment by vincepri** [comment]
I just tried to launch a cluster in us-east-1 and the bootstrap was successful, not sure how to reproduce this :/, do you have a way to paste the output of `/tmp/kubeadm.yml` and the output when you run the script?

**Comment by rbankston** [comment]
kubeadm.yml

```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.2
api:
  controlPlaneEndpoint: heptio-ku-apiloadb-blzq3ml8uy4a-875862043.us-east-2.elb.amazonaws.com:443
apiServerCertSANs:
- 18.220.182.151
apiServerExtraArgs:
  cloud-provider: aws
nodeRegistration:
  name: ip-10-0-16-215.us-east-2.compute.internal
  kubeletExtraArgs:
    cloud-provider: aws
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: tag0aq.ytwrr5hz2xediuhk
  ttl: 0s
  usages:
  - signing
  - authentication
controllerManagerExtraArgs:
  cloud-provider: aws
  allocate-node-cidrs: "false"
featureGates:
  CoreDNS: True
networking:
  podSubnet: 192.168.0.0/16
```
The yaml is valid but when called from the bash script gives that error if using the script to initialize with kubeadm.

**Comment by rbankston** [comment]
Tried to launch in US-EAST-1 as well and received the same failure.

**Comment by detiber** [comment]
We really should be quoting any strings that may include `:` in them

**Comment by vincepri** [comment]
@rbankston I think this should be fixed in https://github.com/heptio/aws-quickstart/pull/224

**Comment by vincepri** [comment]
I think the ELB IP was chosen because this https://github.com/heptio/aws-quickstart/blob/master/scripts/setup-k8s-master.sh.in#L129 was erroring in case we'd specify a dnsname, @chuckha @detiber any suggestions on that

**Comment by ahren1234** [comment]
this is still an issue, and has to do with what was talked about earlier. A correction could be turning this variable into a array and printing elements accordingly. An example is below (without proper validation/sanitation) 


LB_IPV4=($(dig +short example.amazonaws.com))
....
certSANs:                                                                                                                                                                   - "${LB_IPV4[0]}"                                                                                                                                                           - "${LB_IPV4[1]}"
